version: '3.4'

services:
  linkshortnerv1:
    image: linkshortnerv1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7000:7000
